import { LinkCategory, LinkItem } from './types';

export const ALL_LINKS: LinkItem[] = [
  // --- PASSIVE NODES (Bandwidth/Compute) ---
  { id: '39', url: 'https://pawns.app/?r=1112465', title: 'Pawns.app', category: LinkCategory.PASSIVE_NODES, tags: ['Bandwidth', 'Passive', 'PC/Mobile'], recommended: true },
  { id: '45', url: 'https://app.nodepay.ai/register?ref=5pxS8VIIZzNeDSF', title: 'Nodepay.ai', category: LinkCategory.PASSIVE_NODES, tags: ['Bandwidth', 'AI', 'Solana'], recommended: true },
  { id: '49', url: 'https://app.getgrass.io/register?referralCode=XBPRl6U7sAvvzRX', title: 'GetGrass.io', category: LinkCategory.PASSIVE_NODES, tags: ['Bandwidth', 'DePIN', 'Tier 1'], recommended: true },
  { id: '44', url: 'https://hub.playai.network/?ref=dashboard', title: 'PlayAI Hub', category: LinkCategory.PASSIVE_NODES, tags: ['AI', 'Node'] },
  { id: '47', url: 'https://node.optimai.network/register?ref=0EB0B06E', title: 'OptimAI Node', category: LinkCategory.PASSIVE_NODES, tags: ['Node', 'AI'] },
  { id: '48', url: 'https://miningblocks.club/?Referral=35696', title: 'MiningBlocks Club', category: LinkCategory.PASSIVE_NODES, tags: ['Mining Sim'] },
  { id: '41', url: 'https://surfe.be/ext/178882', title: 'Surfe.be', category: LinkCategory.PASSIVE_NODES, tags: ['Extension', 'Ads'] },

  // --- OG FAUCETS (Reliable Drip) ---
  { id: '75', url: 'https://freebitco.in/?r=17006348', title: 'FreeBitco.in', category: LinkCategory.OG_FAUCETS, tags: ['BTC', 'Legendary', 'Hourly'], recommended: true },
  { id: '68', url: 'https://cointiply.com/r/mOnqp', title: 'Cointiply', category: LinkCategory.OG_FAUCETS, tags: ['Survey', 'Faucet', 'Top Tier'], recommended: true },
  { id: '71', url: 'https://faucetpay.io/?r=95880', title: 'FaucetPay', category: LinkCategory.OG_FAUCETS, tags: ['Wallet', 'Aggregator'], recommended: true },
  { id: '67', url: 'https://autofaucet.dutchycorp.space/?r=Autofaucets', title: 'DutchyCorp', category: LinkCategory.OG_FAUCETS, tags: ['Auto', 'Multi-Coin'] },
  { id: '72', url: 'https://firefaucet.win/ref/126786', title: 'FireFaucet', category: LinkCategory.OG_FAUCETS, tags: ['Auto', 'Leveling'] },
  { id: '70', url: 'https://earnbitmoon.club/?ref=265500', title: 'EarnBitMoon', category: LinkCategory.OG_FAUCETS, tags: ['Faucet'] },
  { id: '83', url: 'https://viefaucet.com?r=6380ee9189dc9d60cddeaf22', title: 'VieFaucet', category: LinkCategory.OG_FAUCETS, tags: ['Faucet'] },
  
  // --- HOURLY LOOT (Pick Games) ---
  { id: '84', url: 'https://dogepick.io/?ref=limana', title: 'DogePick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'Doge'], recommended: true },
  { id: '85', url: 'https://litepick.io/?ref=source', title: 'LitePick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'LTC'] },
  { id: '86', url: 'https://polpick.io/?ref=dashboard', title: 'PolPick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'Matic'] },
  { id: '87', url: 'https://solpick.io/?ref=dashboard', title: 'SolPick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'Solana'] },
  { id: '88', url: 'https://suipick.io/?ref=dashboard', title: 'SuiPick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'Sui'] },
  { id: '89', url: 'https://tonpick.game/?ref=dashboard', title: 'TonPick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'TON'] },
  { id: '90', url: 'https://usdpick.io?ref=fAYHy9teXq', title: 'USDPick', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly', 'Stable'] },
  { id: '73', url: 'https://freebch.in?ref=GYbcNKDvc8', title: 'FreeBCH', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '74', url: 'https://freebnb.in?ref=t3guZH6504', title: 'FreeBNB', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '76', url: 'https://freearb.in?ref=DT-wOppZxs', title: 'FreeArb', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '77', url: 'https://freeshib.in?ref=Q4gBET4aub', title: 'FreeShib', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '78', url: 'https://freesui.in?ref=2OBNF6surV', title: 'FreeSui', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '79', url: 'https://freetoncoin.in?ref=4oDtavonot', title: 'FreeTon', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '80', url: 'https://freetron.in?ref=D96wTKmOPD', title: 'FreeTron', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '81', url: 'https://freetrump.in?ref=Qzx6sqZz1E', title: 'FreeTrump', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },
  { id: '82', url: 'https://freexrp.in?ref=sKqECBxDCJ', title: 'FreeXRP', category: LinkCategory.HOURLY_LOOT, tags: ['Hourly'] },

  // --- MICRO WORK (PTC/Captcha) ---
  { id: '32', url: 'https://2captcha.com/?from=9690712', title: '2Captcha', category: LinkCategory.MICRO_WORK, tags: ['Work', 'Solver', 'Fiat'], recommended: true },
  { id: '36', url: 'https://www.coinpayu.com/?r=dashboard', title: 'CoinPayU', category: LinkCategory.MICRO_WORK, tags: ['Ads', 'Top Tier'], recommended: true },
  { id: '34', url: 'https://r.adbtc.top/1169353', title: 'AdBTC', category: LinkCategory.MICRO_WORK, tags: ['Ads', 'Sats'] },
  { id: '35', url: 'https://btcadspace.com/ref/source', title: 'BTC AdSpace', category: LinkCategory.MICRO_WORK, tags: ['Ads'] },
  { id: '42', url: 'https://timebucks.com/?refID=219093340', title: 'TimeBucks', category: LinkCategory.MICRO_WORK, tags: ['Survey', 'Fiat'] },
  { id: '37', url: 'https://everve.net/ref/678797/', title: 'Everve', category: LinkCategory.MICRO_WORK, tags: ['Social'] },
  { id: '38', url: 'https://freeward.net/ref/7pex8', title: 'Freeward', category: LinkCategory.MICRO_WORK, tags: ['Offers'] },
  { id: '40', url: 'https://rewardvid.com?ref=ETqLenDf', title: 'RewardVid', category: LinkCategory.MICRO_WORK, tags: ['Video'] },
  { id: '43', url: 'https://earnviv.com/?r=36182', title: 'EarnViv', category: LinkCategory.MICRO_WORK, tags: ['Offers'] },
  { id: '65', url: 'https://www.publish0x.com/?a=OpnelZ1bKB', title: 'Publish0x', category: LinkCategory.MICRO_WORK, tags: ['Reading', 'Crypto'] },
  
  // --- AIRDROP OPS (Testnet/Faucets) ---
  { id: '17', url: 'https://parthenon.movementlabs.xyz/dashboard', title: 'Movement Labs', category: LinkCategory.AIRDROP_OPS, tags: ['L2', 'Testnet'], recommended: true },
  { id: '7', url: 'https://testnet.huddle01.com/leaderboard', title: 'Huddle01', category: LinkCategory.AIRDROP_OPS, tags: ['DePIN', 'Testnet'] },
  { id: '1', url: 'https://maxsee.io?k=E7967767', title: 'MaxSee', category: LinkCategory.AIRDROP_OPS, tags: ['Watch2Earn', 'New'] },
  { id: '2', url: 'https://portal.pi2.network/game', title: 'Pi2 Network', category: LinkCategory.AIRDROP_OPS, tags: ['Testnet'] },
  { id: '3', url: 'https://neuraverse.neuraprotocol.io/?section=leaderboard', title: 'Neuraverse', category: LinkCategory.AIRDROP_OPS, tags: ['Protocol'] },
  { id: '4', url: 'https://app.piggycell.io/?ref=5EOPZ8', title: 'PiggyCell', category: LinkCategory.AIRDROP_OPS, tags: ['App'] },
  { id: '5', url: 'https://testnet.lifeai.io/ref?code=WFNY7Z3', title: 'LifeAI Testnet', category: LinkCategory.AIRDROP_OPS, tags: ['AI'] },
  { id: '6', url: 'https://nebulai.network/final-test?invite_by=D1F1kn', title: 'Nebulai Network', category: LinkCategory.AIRDROP_OPS, tags: ['Final Test'] },
  { id: '10', url: 'https://operator.olivianetwork.com?ref=#OPJ3FIK2', title: 'Olivia Network', category: LinkCategory.AIRDROP_OPS, tags: ['Operator'] },
  { id: '11', url: 'https://devnet-dapp.rayls.com/', title: 'Rayls Devnet', category: LinkCategory.AIRDROP_OPS, tags: ['Devnet'] },
  { id: '12', url: 'https://cedomis.xyz/dashboard', title: 'Cedomis', category: LinkCategory.AIRDROP_OPS, tags: ['Dashboard'] },
  { id: '13', url: 'https://testnet.pharosnetwork.xyz/experience?inviteCode=RfgFyrjEUeC728lB', title: 'Pharos Network', category: LinkCategory.AIRDROP_OPS, tags: ['Testnet'] },
  { id: '14', url: 'https://app.namso.network/dashboard/?ref=A339FDFAE39E', title: 'Namso Network', category: LinkCategory.AIRDROP_OPS, tags: ['Testnet'] },
  { id: '16', url: 'https://proving-grounds.brevis.network/VQcpfa', title: 'Brevis ZK', category: LinkCategory.AIRDROP_OPS, tags: ['ZK', 'Proving'] },

  // --- WEB3 GAMING ---
  { id: '22', url: 'https://play.immutable.com/referral/share/8gkaZR?utm_source=referral', title: 'Immutable X', category: LinkCategory.WEB3_GAMING, tags: ['Ecosystem', 'Top Tier'], recommended: true },
  { id: '27', url: 'https://rollercoin.com/?r=kcq1472k', title: 'RollerCoin', category: LinkCategory.WEB3_GAMING, tags: ['Sim', 'Classic'] },
  { id: '26', url: 'https://t.me/gamee/start?startapp=eyJyZWYiOjMzMzYwMDY0MH0', title: 'Gamee (TG)', category: LinkCategory.WEB3_GAMING, tags: ['Telegram', 'Mobile'] },
  { id: '18', url: 'https://s.trex.xyz/lltWFq', title: 'Trex.xyz', category: LinkCategory.WEB3_GAMING, tags: ['Game'] },
  { id: '20', url: 'https://quests.yom.net/loyalty?referral_code=I0SWSZ6V', title: 'YOM Quests', category: LinkCategory.WEB3_GAMING, tags: ['Metaverse'] },
  { id: '21', url: 'https://nomstead.com/?ref=dhqgys6b', title: 'Nomstead', category: LinkCategory.WEB3_GAMING, tags: ['Game'] },
  { id: '23', url: 'https://prometheansaga.com?r=u9Jva2XK', title: 'Promethean Saga', category: LinkCategory.WEB3_GAMING, tags: ['RPG'] },
  { id: '24', url: 'https://app.luckyx.world/?p=Yie918', title: 'LuckyX World', category: LinkCategory.WEB3_GAMING, tags: ['Arcade'] },
  { id: '28', url: 'https://simplebits.io/ref/0rd4li1cSLTL', title: 'SimpleBits', category: LinkCategory.WEB3_GAMING, tags: ['Sim'] },
  { id: '29', url: 'https://limercoin.com/?ref=4i6ljids', title: 'LimerCoin', category: LinkCategory.WEB3_GAMING, tags: ['Sim'] },
  { id: '30', url: 'https://luckywatch.pro/u/0oqit', title: 'LuckyWatch', category: LinkCategory.WEB3_GAMING, tags: ['Game'] },

  // --- QUEST BOARD ---
  { id: '57', url: 'https://dscvr.one/invite/dashboard?ur=e99a9b5f-4449-4382-943b-71579aadfa85', title: 'DSCVR', category: LinkCategory.QUEST_BOARD, tags: ['SocialFi', 'Solana'], recommended: true },
  { id: '63', url: 'https://skynet.certik.com/quest/signup?referralId=4324d09a-bf19-437c-8635-645a52dbf136', title: 'Certik Skynet', category: LinkCategory.QUEST_BOARD, tags: ['Security', 'Quests'] },
  { id: '50', url: 'https://app.optimai.im/generate-tweet', title: 'OptimAI Social', category: LinkCategory.QUEST_BOARD, tags: ['Social'] },
  { id: '51', url: 'https://app.fight.id/signup?code=FEFDB806', title: 'Fight.id', category: LinkCategory.QUEST_BOARD, tags: ['Social'] },
  { id: '52', url: 'https://yupp.ai/join/ruby-square-engine', title: 'Yupp.ai', category: LinkCategory.QUEST_BOARD, tags: ['AI'] },
  { id: '53', url: 'https://surflayer.xyz?ref=8d285aa34e', title: 'SurfLayer', category: LinkCategory.QUEST_BOARD, tags: ['Social'] },
  { id: '55', url: 'https://my.aidapp.com/?refCode=XE9RnUdhxDi1XNw', title: 'AiDapp', category: LinkCategory.QUEST_BOARD, tags: ['AI'] },
  { id: '56', url: 'https://app.sapien.io/t/airdrop', title: 'Sapien', category: LinkCategory.QUEST_BOARD, tags: ['Data'] },
  { id: '58', url: 'https://app.codatta.io/referral/a4591r', title: 'Codatta', category: LinkCategory.QUEST_BOARD, tags: ['Data'] },
  { id: '59', url: 'https://mission.superintent.ai/?referralCode=eIJAOWtvmB', title: 'SuperIntent', category: LinkCategory.QUEST_BOARD, tags: ['AI'] },
  { id: '60', url: 'https://app.gata.xyz?invite_code=8epdx7rg', title: 'Gata.xyz', category: LinkCategory.QUEST_BOARD, tags: ['Community'] },
  { id: '61', url: 'https://dashboard.aro.network/signup?referral=GJIXM0', title: 'Aro Network', category: LinkCategory.QUEST_BOARD, tags: ['DePIN'] },
  { id: '62', url: 'https://blockstreet.money/dashboard?invite_code=mvEz8G', title: 'BlockStreet', category: LinkCategory.QUEST_BOARD, tags: ['Finance'] },

  // --- INFRASTRUCTURE ---
  { id: '91', url: 'https://accounts.binance.com/register?ref=49685937', title: 'Binance', category: LinkCategory.INFRASTRUCTURE, tags: ['Exchange', 'Tier 1'], recommended: true },
  { id: '92', url: 'https://www.mexc.com/auth/signup?inviteCode=2pLgC', title: 'MEXC Global', category: LinkCategory.INFRASTRUCTURE, tags: ['Exchange', 'Low Cap Gems'] },
  { id: '98', url: 'https://eth.blockscout.com/?ref=6RZXK3', title: 'Blockscout', category: LinkCategory.INFRASTRUCTURE, tags: ['Explorer', 'Tools'] },
  { id: '96', url: 'https://www.rainbow.me/points?ref=66K7GM', title: 'Rainbow Wallet', category: LinkCategory.INFRASTRUCTURE, tags: ['Wallet', 'Points'] },
  { id: '97', url: 'https://newshare.bwb.global/en/referralLanding?inviteCode=ZnYvar&type=card', title: 'Bitget Wallet', category: LinkCategory.INFRASTRUCTURE, tags: ['Wallet', 'BWB'] },
  { id: '95', url: 'https://sosovalue.com/join/0DCN0PVQ', title: 'SoSoValue', category: LinkCategory.INFRASTRUCTURE, tags: ['Analytics'] },
  { id: '99', url: 'https://dashboard.3dos.io/register?ref_code=6d8572', title: '3Dos', category: LinkCategory.INFRASTRUCTURE, tags: ['Tool'] },
  { id: '106', url: 'https://signup.billions.network/?rc=IMENAAXD', title: 'Billions Network', category: LinkCategory.INFRASTRUCTURE, tags: ['High Yield'] },
  { id: '107', url: 'https://t.me/EtherDROPS_bot?start=promo_OYJAP5', title: 'EtherDrops Bot', category: LinkCategory.INFRASTRUCTURE, tags: ['Bot', 'Tracking'] },
];

export const CATEGORY_STYLES: Record<LinkCategory, { color: string, icon: string, desc: string }> = {
  [LinkCategory.PASSIVE_NODES]: { color: 'bg-emerald-500', icon: 'Wifi', desc: 'Install -> Connect -> Earn while sleeping.' },
  [LinkCategory.HOURLY_LOOT]: { color: 'bg-amber-500', icon: 'Clock', desc: 'Set an alarm. Claim every 60 minutes.' },
  [LinkCategory.OG_FAUCETS]: { color: 'bg-blue-500', icon: 'Droplets', desc: 'Old faithfuls. Slow but guaranteed payouts.' },
  [LinkCategory.MICRO_WORK]: { color: 'bg-slate-500', icon: 'Hammer', desc: 'Trade time for token. Captchas, ads, surveys.' },
  [LinkCategory.AIRDROP_OPS]: { color: 'bg-purple-500', icon: 'Rocket', desc: 'Testnet interactions. Future jackpot hunting.' },
  [LinkCategory.WEB3_GAMING]: { color: 'bg-pink-500', icon: 'Gamepad2', desc: 'Play games, own assets, earn tokens.' },
  [LinkCategory.QUEST_BOARD]: { color: 'bg-indigo-500', icon: 'Swords', desc: 'Social tasks. Follow, RT, Join Discord.' },
  [LinkCategory.INFRASTRUCTURE]: { color: 'bg-cyan-600', icon: 'Wrench', desc: 'Wallets, exchanges, and essential tools.' },
  [LinkCategory.RISK_LABS]: { color: 'bg-red-500', icon: 'Skull', desc: 'Experimental. Don\'t invest what you can\'t lose.' },
};
